# This is a basic workflow to help you get started with Actions
# This script can be added to the GitHub Actions workflow of repository A

name: Upload cv.pdf to repository B

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  upload_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PersonalResume
      uses: actions/checkout@v2

    - name: Get cv.pdf
      run: |
        curl -o cv.pdf https://raw.githubusercontent.com/${{ GITHUB_REPOSITORY }}/${{ GITHUB_SHA }}/cv.pdf

    - name: Checkout filippovisconti.github.io
      uses: actions/checkout@v2
      with:
        repository: filippovisconti.github.io
        ref: main
        token: ${{ env.GITHUB_TOKEN }}

    - name: Copy cv.pdf to repository B
      run: |
        cp cv.pdf filippovisconti.github.io/files/cv.pdf

    - name: Commit and push changes to repository B
      run: |
        cd filippovisconti.github.io
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add cv.pdf
        git commit -m "Update cv.pdf"
        git push origin main

