# This is a basic workflow to help you get started with Actions
# This script can be added to the GitHub Actions workflow of repository A

name: Upload cv.pdf to filippovisconti.github.io

on:
  push:
    branches:
      - main

jobs:
  upload_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout filippovisconti.github.io
      uses: actions/checkout@v3
      with:
        repository: filippovisconti/filippovisconti.github.io
        ref: main

    - name: Commit and push changes to repository B
      run: |
        curl -o cv.pdf https://github.com/filippovisconti/PersonalResume/raw/main/cv.pdf
        mv cv.pdf files/
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add files/cv.pdf
        git commit -a -m "Update cv.pdf"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.API_KEY }}
        branch: main
