# This is a basic workflow to help you get started with Actions
# This script can be added to the GitHub Actions workflow of repository A

name: Upload cv.pdf to filippovisconti.github.io

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  upload_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PersonalResume
      uses: actions/checkout@v3

    - name: Checkout filippovisconti.github.io
      uses: actions/checkout@v3
      with:
        repository: filippovisconti.github.io
        ref: main
        token: ${{ env.GITHUB_TOKEN }}

    - name: Commit and push changes to repository B
      run: |
        cd filippovisconti.github.io
        curl -o cv.pdf https://github.com/filippovisconti/PersonalResume/raw/main/cv.pdf
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add cv.pdf
        git commit -m "Update cv.pdf"
        git push origin main

